"""Dataset-specific acquisition adapters.

These adapters sit behind the shared acquisition contracts while retaining the
source-specific validation rules needed to fail closed.
"""

from autovalue_ml.acquisition.sources.huggingface_candidates import (
    CARSON_SCHEMA_MAPPING_VERSION,
    CARSON_SHIVELY_SILVER_AUDIT_SPEC,
    CARSON_SHIVELY_SPEC,
    YOAD22_CRAIGSLIST_SPEC,
    YOAD_SCHEMA_MAPPING_VERSION,
    CandidateNormalizationBatch,
    CandidateRecordRejection,
    CandidateVehicleRecord,
    normalize_accident_status,
    normalize_candidate_records,
    normalize_carson_record,
    normalize_clean_title,
    normalize_yoad_record,
    parse_mileage_text,
)
from autovalue_ml.acquisition.sources.kaggle_us_sales_cars import (
    KAGGLE_US_SALES_CARS_HEADER,
    KaggleUSSalesCarsArtifactSet,
    KaggleUSSalesCarsError,
    KaggleUSSalesCarsMetrics,
    KaggleUSSalesCarsReview,
    KaggleUSSalesCarsTrainingRows,
    load_kaggle_us_sales_cars_review,
    prepare_kaggle_us_sales_cars_training_rows,
    process_kaggle_us_sales_cars_csv,
    require_kaggle_us_sales_cars_ml_training_approval,
    verify_kaggle_us_sales_cars_artifact_set,
)
from autovalue_ml.acquisition.sources.kaggle_us_sales_cars_split import (
    KaggleUSSalesCarsSplitArtifactSet,
    KaggleUSSalesCarsSplitError,
    KaggleUSSalesCarsSplitMetrics,
    KaggleUSSalesCarsSplitTrainingRows,
    VerifiedKaggleUSSalesCarsSplit,
    build_kaggle_us_sales_cars_group_split,
    prepare_kaggle_us_sales_cars_split_training_rows,
    verify_kaggle_us_sales_cars_group_split,
)
from autovalue_ml.acquisition.sources.kaggle_vehicle_sales import (
    KAGGLE_VEHICLE_SALES_HEADER,
    KaggleCandidateArtifactSet,
    KaggleIngestionMetrics,
    KaggleVehicleSalesError,
    KaggleVehicleSalesReview,
    load_kaggle_vehicle_sales_review,
    prepare_kaggle_training_rows,
    process_kaggle_vehicle_sales_csv,
    require_kaggle_ml_training_approval,
    verify_kaggle_candidate_artifact_set,
)
from autovalue_ml.acquisition.sources.kaggle_vehicle_sales_split import (
    KaggleVehicleSalesSplitArtifactSet,
    KaggleVehicleSalesSplitError,
    KaggleVehicleSalesSplitMetrics,
    KaggleVehicleSalesSplitPolicy,
    KaggleVehicleSalesTrainingRows,
    TrainingRow,
    VerifiedKaggleVehicleSalesSplit,
    load_kaggle_vehicle_sales_split_policy,
    prepare_kaggle_vehicle_sales_training_rows,
    process_kaggle_vehicle_sales_split,
    verify_kaggle_vehicle_sales_split_artifact_set,
)

__all__ = [
    "CARSON_SCHEMA_MAPPING_VERSION",
    "CARSON_SHIVELY_SILVER_AUDIT_SPEC",
    "CARSON_SHIVELY_SPEC",
    "CandidateNormalizationBatch",
    "CandidateRecordRejection",
    "CandidateVehicleRecord",
    "KAGGLE_US_SALES_CARS_HEADER",
    "KAGGLE_VEHICLE_SALES_HEADER",
    "KaggleCandidateArtifactSet",
    "KaggleIngestionMetrics",
    "KaggleUSSalesCarsArtifactSet",
    "KaggleUSSalesCarsError",
    "KaggleUSSalesCarsMetrics",
    "KaggleUSSalesCarsReview",
    "KaggleUSSalesCarsSplitArtifactSet",
    "KaggleUSSalesCarsSplitError",
    "KaggleUSSalesCarsSplitMetrics",
    "KaggleUSSalesCarsSplitTrainingRows",
    "KaggleUSSalesCarsTrainingRows",
    "KaggleVehicleSalesError",
    "KaggleVehicleSalesReview",
    "KaggleVehicleSalesSplitArtifactSet",
    "KaggleVehicleSalesSplitError",
    "KaggleVehicleSalesSplitMetrics",
    "KaggleVehicleSalesSplitPolicy",
    "KaggleVehicleSalesTrainingRows",
    "TrainingRow",
    "YOAD22_CRAIGSLIST_SPEC",
    "YOAD_SCHEMA_MAPPING_VERSION",
    "VerifiedKaggleUSSalesCarsSplit",
    "VerifiedKaggleVehicleSalesSplit",
    "build_kaggle_us_sales_cars_group_split",
    "load_kaggle_vehicle_sales_split_policy",
    "load_kaggle_vehicle_sales_review",
    "normalize_accident_status",
    "normalize_candidate_records",
    "normalize_carson_record",
    "normalize_clean_title",
    "normalize_yoad_record",
    "parse_mileage_text",
    "load_kaggle_us_sales_cars_review",
    "prepare_kaggle_training_rows",
    "prepare_kaggle_us_sales_cars_split_training_rows",
    "prepare_kaggle_us_sales_cars_training_rows",
    "prepare_kaggle_vehicle_sales_training_rows",
    "process_kaggle_vehicle_sales_split",
    "process_kaggle_vehicle_sales_csv",
    "process_kaggle_us_sales_cars_csv",
    "require_kaggle_ml_training_approval",
    "require_kaggle_us_sales_cars_ml_training_approval",
    "verify_kaggle_candidate_artifact_set",
    "verify_kaggle_us_sales_cars_artifact_set",
    "verify_kaggle_us_sales_cars_group_split",
    "verify_kaggle_vehicle_sales_split_artifact_set",
]
